### ISSUE TITLE
Don't panic on unknown tags

### ISSUE THREAD

**Issue by alexkreidler** [mathiversen/html-parser#1]
This line: https://github.com/mathiversen/html-parser/blob/5c9f3aac5583a61305d628385630b0ba63d2bbf6/src/dom/mod.rs#L191

means that any unknown tag (in my case it was `el_process_instruct`) will cause a panic. Please just return an error here, otherwise the API is really difficult to work with.

You may want to also check over to make sure that there are no other panics in the codebase. Generally IMHO, a parsing library should never panic.

**Comment by mathiversen** [comment]
Thanks for submitting this issue! I've been away on vacation but I'll try to find some time this weekend. Pr's are of course always welcome :)

**Comment by mathiversen** [comment]
Fixed in 0.5.0
