### ISSUE TITLE
Include position of elements in source

### ISSUE THREAD

**Issue by kaleidawave** [mathiversen/html-parser#13]
(feature request)

Would really like some field on structures like [`Element`](https://docs.rs/html_parser/0.6.2/html_parser/struct.Element.html) which would contain some data which reveals it position in the source input. 

e.g. parsing the following

```html
<div>
    <h1>Hi!</h1>
</div>
```

```rust
let h1: Element = ...;
assert_eq!(h1.position(), Span { line_start: 1, line_end: 1, column_start: 4, column_end: 16 })
```

This would be really useful in the example of checking HTML against some rules, if it doesn't meet a rule would be nice to give a position to where the rule fails.

Not familiar with pest but wondering if [this could be used somehow](https://docs.rs/pest/2.1.3/pest/struct.Span.html)

**Comment by mathiversen** [comment]
Nothing :) Just published a new release with all the new updates. Sorry for taking so long!
