### ISSUE TITLE
attr can't parse space

### ISSUE THREAD

**Issue by zhuxiujia** [mathiversen/html-parser#15]
the string is__________'select_by_condition '
parse result string is_'select_by_condition'
html-parser lost attr  space.
for example:
```html
    <select attr="select_by_condition ">
        select * from table where 
        <if test="id > 0 && id == 1"> id </if>
   </select>
```

**Comment by mathiversen** [comment]
Sorry i misread, I'll have a look at why the whitespace is stripped

**Comment by zhuxiujia** [comment]
> 

Thanks for your reply, and I found that the string '\n' and 'Spaces' were missing.
but, [html5ever](https://crates.io/crates/html5ever) do not lost this data('\n          ').

**Comment by zhuxiujia** [comment]
> Sorry i misread, I'll have a look at why the whitespace is stripped

Thanks for your reply, and I found that the string '\n' and 'Spaces' were missing.
but, [html5ever](https://crates.io/crates/html5ever) do not lost this data('\n ').

**Comment by mathiversen** [comment]
this should fix your issue: https://github.com/mathiversen/html-parser/pull/16

**Comment by mathiversen** [comment]
solved
