### ISSUE TITLE
implement Clone for Node

### ISSUE THREAD

**Issue by zhiburt** [mathiversen/html-parser#2]
Clearly it's inefficient to do a `clone` on a deep node but sometimes it's useful for example

```rust
let dom = parse(html);
let expected = dom.children.clone();

// do stuff with dom

assert_eq!(dom.children, expected)
```

Might this example doesn't provide a plain explanation why it may be useful, but it is?

___

Implementation could be done by `derive`

**Comment by mathiversen** [comment]
Thanks for submitting this issue! I've been away on vacation but I'll try to find some time this weekend. Pr's are of course always welcome :)

**Comment by mathiversen** [comment]
added support for cloning in 0.5.0
